### ISSUE TITLE
not always opening browser

### ISSUE THREAD

**Issue by maxandersen** [sheriferson/Visualize.mmBundle#2] opened 2015-08-08 06:22 UTC
not sure what is going on but sometimes on a selection the browser never opens up.

If choose a different selection it does show up.

Have a feeling I got some specific messages that trigger it to fail. Any ideas ?

**Comment by freron** [comment] 2015-08-08 17:56
You could do a binary search for such a message, but it's not obvious how any messages could trigger opening Safari to fail. They would usually make what is displayed in Safari fail.

Have you tried launching from the Terminal and see if any errors are output?

```
/Applications/MailMate.app/Contents/MacOS/MailMate
```

**Comment by sheriferson** [comment] 2015-08-08 17:57
Thanks for reporting this.
I'm assuming that failure is not tied to whether Safari was already running or not? there was a recent issue where the command would fail if Safari wasn't already running but Benny fixed it in a recent update. 

Another question: can you tell if failure only happens with either "Emails by time" or "Emails by sender"? Or does a selection that fails fail with either command?

In the meantime, I tried a bunch of mailboxes including mailing lists, with different selections ranging from 2 emails to 5000 emails and didn't run into an instance where the browser didn't open up, so it could be a certain message(s) that you have. <del>I'm communicating with Benny on how best to troubleshoot this.</del> He's already commented on the issue :)

**Comment by maxandersen** [comment] 2015-08-09 08:27
I see no output when running from command line (actually surprised by that since I recalled seeing plenty output in past - maybe I need to set some flag?)

And afaics it fails consistently on both types of visualization.

**Comment by maxandersen** [comment] 2015-08-09 08:27
...and I can try do a binary search later today when i'm crossing the atlantic :)

**Comment by sheriferson** [comment] 2016-01-18 02:28
As far as I can tell, this is a MailMate issue likely caused by a malformed/corrupt message, and so it's not something I can handle in my plugin. If a corrupt message prevents MailMate from exporting a `csv` file to `${TMPDIR}/com.freron.MailMate.Visualize.csv`, then it's something that MailMate has to handle.

I'm closing this issue, but if the plugin still fails even when MailMate exports the csv file, do let me know.

**Closed as completed by sheriferson** 2016-01-18 02:28 UTC

**Comment by freron** [comment] 2016-01-18 08:53
And I would of course welcome a reproducible example of a message triggering this issue. It's very likely some general issue which really needs to be fixed.

**Comment by maxandersen** [comment] 2016-01-18 09:28
I haven't been able to reproduce in a while - but i'll keep an eye out and report back if it happens again.
